### ISSUE TITLE
Is there any precompiled sqlite3.dll with CEVFS support?

### ISSUE THREAD

**Issue by HamidZaeri** [ryanhomer/sqlite3-compression-encryption-vfs#1]
Hi 
I'm no expert, just wondered if there is such a dll file so all compression applied on the fly.

**Comment by techrah** [comment]
Unfortunately, I've only ever used this on Mac, so I don't have any precompiled DLL and have no idea what you're up against to get this working on another platform.

Also, this library does not include any specific encryption or compression code. You'll need to figure out what is available on your platform and implement the appropriate encryption/compression functions, similar to this [example](https://github.com/ryanhomer/sqlite3-compression-encryption-vfs/blob/65bdececa1adfc7710126e84546ce5cef2a3bb0a/cevfs_example/main.c).
