### ISSUE TITLE
compression only mode

### ISSUE THREAD

**Issue by AndreyArsov** [ryanhomer/sqlite3-compression-encryption-vfs#3]
It looks possible to use only compression mode and not include encryption functions.
In fact cevfsRead seems to deal with that (p->bEncryptionEnabled == false), while cevfsWrite doesn't, is there an easy fix for that?

**Comment by techrah** [comment]
Hi @AndreyArsov. Thanks for reporting this. Not sure if you still need help but I've put up a preliminary pull request (#4) for this. I don't really use CEVFS anymore and not sure how well it's holding up these days. I had some errors getting the original code to work locally and had to set a block size (`1024` or `2048` should do). I've updated the README to explain how to do this.

**Comment by AndreyArsov** [comment]
Thanks, I made similar changes and can verify that this works. I was hitting crashes however on big tables when the page size was different from 4K. Usually these crashes were happening in the memcpy operations.

**Comment by AndreyArsov** [comment]
btw, I was using this on linux based system by commenting the mac encyption APIs, and the implementation works, just as fyi, in case anyone needs the info.

**Comment by techrah** [comment]
Thanks for the feedback. Good to know that it's working on a Linux-based platform. I'll work on trying to identify the page size issue.
